name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockertest:test1
    - name: Save the image
      run: docker save dockertest > image.tar
#    - name: Copy single file to remote
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: image.tar
#        remote: image.tar
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        port: ${{ secrets.PORT }}
#        privateKey: ${{ secrets.SSH_KEY }}
#        passphrase: ${{ secrets.PASSPHRASE }}

#    - uses: jitterbit/get-changed-files@v1
#    - name: Image Builder
#      id: files
#      run: |
#        for changed_file in ${{ steps.files.outputs.all }}; do
#          echo "Do something with this ${changed_file}."
#        done

#    - name: Get changed files
#      id: changed-files
#      uses: tj-actions/changed-files@v33
#    - name: List all changed files
#      run: |
#        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#          echo "$file was changed"
#        done

    - name: Get changed files in the docs folder
      id: changed-files-specific
      uses: tj-actions/changed-files@v33
      with:
        files: |
          Dockerfiles/**

    - name: Run step if any file(s) in the docs folder change
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: |
        for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
          echo "$file was changed"
          docker build . --file $file --tag new_file
          docker save new_file > new_image.tar
        done
