name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockertest:test1
    - name: Save the image
      run: docker save dockertest > image.tar
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: image.tar
        remote: image.tar
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        privateKey: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
